### ISSUE TITLE
I have one problem

### ISSUE THREAD

**Issue by w0330t** [rix1337/docker-gphotos-sync#1]
`Afterwards you need to sign into the application once which cannot be done headlessly (using the "Syncing" command)
`

I don't know this "Syncing" where to run,

**Comment by rix1337** [comment]
It is at the bottom of the readme. Run the command on your docker host.

![grafik](https://user-images.githubusercontent.com/9930448/81266369-f0c77200-9044-11ea-894e-9ec335b1e1db.png)
