### ISSUE TITLE
Resolution Change

### ISSUE THREAD

**Issue by The-IcEDFiRE** [rix1337/docker-gphotos-sync#4]
Hi, Is there a way to download the full resolution of a photo/video? Even though on Google Photos the photos and videos are uploaded with "original" quality, when I download using the gphotos-sync the videos are being downscaled from 4K to 1080p. Photos are also compressed for eg a photo of 9.5MB is compressed to 2.5MB. Thanks.

**Comment by rix1337** [comment]
You should ask that at the creators repo
This here is only a wrapper for https://github.com/gilesknap/gphotos-sync
