### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by Mr-Lucas** [rix1337/docker-gphotos-sync#5]
When I click on the link in the command window, to obtain the response token, I receive the following authorization error.  Could you help me figure out what is wrong?  Thanks!

Error 400: invalid_request

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.

You can let the app developer know that this app doesn't comply with one or more Google validation rules.
Request Details
The content in this section has been provided by the app developer. This content has not been reviewed or verified by Google.
If you’re the app developer, make sure that these request details comply with Google policies.
redirect_uri: urn:ietf:wg:oauth:2.0:oob

**Comment by Mr-Lucas** [comment]
I think I sorted it.  I didn't have any scope in the consent screen.  Added it is now indexing and downloading photos, according to the console.


Photos Library API | .../auth/photoslibrary.readonly | View your Google Photos library

**Comment by rix1337** [comment]
Sounds good
