### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by mabartuccio** [rix1337/docker-gphotos-sync#6]
Until yeesterday it worked very fine, with le last update i receive the follow error: 
05-18 13:26:23 WARNING gphotos-sync 3.0.0 2022-05-18 13:26:23.173839
05-18 13:26:23 WARNING EXITING: database is locked
i made a total uninstall and a fresh installation, same problem, any idea?

**Comment by rix1337** [comment]
Sounds like an issue with the tool itself, not this container.

Please open an issue at the official ghotos-sync repo
