### ISSUE TITLE
EXITING: database is locked

### ISSUE THREAD

**Issue by Ondra5382CZ** [rix1337/docker-gphotos-sync#7]
Hi.
I use UnRaidOS with docker and created my client_secret.json. But after entering the cmd, I got warning and it stopped. 

root@Tower:~# docker exec -it GooglePhotosSync gphotos-sync /mnt/user/Downloads/import
05-28 05:10:10 WARNING  gphotos-sync 3.0.0 2022-05-28 05:10:10.410105 
05-28 05:10:10 WARNING  EXITING: database is locked 

Do you know where the problem might be?

**Comment by rix1337** [comment]
That error is coming from gphotos sync. Please open an issue at their repo.
